[features]
seeds = false
skip-lint = false

[programs.localnet]
billions_bounty = "4ZGXVxuYtaWE3Px4MRingBGSH1EhotBAsFFruhVQMvJK"

[programs.devnet]
billions_bounty = "4ZGXVxuYtaWE3Px4MRingBGSH1EhotBAsFFruhVQMvJK"

[programs.mainnet]
billions_bounty = "4ZGXVxuYtaWE3Px4MRingBGSH1EhotBAsFFruhVQMvJK"

[registry]
url = "https://api.apr.dev"

[toolchain]
anchor_version = "0.28.0"


[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./test/**/*.ts"

[test]
startup_wait = 5000
