[features]
seeds = false
skip-lint = false

[programs.localnet]
billions_bounty_v2 = "HDAfSw1n9o9iZynfEP54tnCf2KRa2cPVFnpTRFtM7Cfm"

[programs.devnet]
billions_bounty_v2 = "HDAfSw1n9o9iZynfEP54tnCf2KRa2cPVFnpTRFtM7Cfm"

[programs.mainnet]
billions_bounty_v2 = "HDAfSw1n9o9iZynfEP54tnCf2KRa2cPVFnpTRFtM7Cfm"

[registry]
url = "https://api.apr.dev"

[toolchain]
anchor_version = "0.30.1"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tests/**/*.ts"

[test]
startup_wait = 5000

